const actionTypes = {
    GET_HOME: 'GET_HOME',
    IS_LOADING: 'IS_LOADING',
    IS_PLAYING: 'IS_PLAYING',
    IS_TYPING: 'IS_TYPING',
    IS_SEARCHING: 'IS_SEARCHING',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_CURRENT_SONG_DETAIL: 'SET_CURRENT_SONG_DETAIL',
    SET_RECENT_SONGS_LIST: 'SET_RECENT_SONGS_LIST',
    SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_PLAYLIST_ID: 'SET_PLAYLIST_ID',
    SET_PLAYLIST: 'SET_PLAYLIST',
};

export default actionTypes;
