const actionTypes = {
    GET_HOME: 'GET_HOME',
    IS_LOADING: 'IS_LOADING',
    IS_PLAYING: 'IS_PLAYING',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_PLAYLIST_ID: 'SET_PLAYLIST_ID',
    SET_CURRENT_SONG_DETAIL: 'SET_CURRENT_SONG_DETAIL',
    SET_PLAYLIST: 'SET_PLAYLIST',
};

export default actionTypes;
