const actionTypes = {
    GET_HOME: 'GET_HOME',
    GET_CHART_PAGE: 'GET_CHART_PAGE',
    GET_NEW_RELEASE: 'GET_NEW_RELEASE',
    SET_TOP_100: 'SET_TOP_100',
    IS_LOADING: 'IS_LOADING',
    IS_PLAYING: 'IS_PLAYING',
    IS_TYPING: 'IS_TYPING',
    IS_SEARCHING: 'IS_SEARCHING',
    IS_SHOW_RIGHT_SIDEBAR: 'IS_SHOW_RIGHT_SIDEBAR',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_CURRENT_SONG_DETAIL: 'SET_CURRENT_SONG_DETAIL',
    SET_RECENT_SONGS_LIST: 'SET_RECENT_SONGS_LIST',
    SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_SEARCH_PARAMS: 'SET_SEARCH_PARAMS',
    SET_PLAYLIST_ID: 'SET_PLAYLIST_ID',
    SET_PLAYLIST: 'SET_PLAYLIST',
    SET_SCREEN_WIDTH: 'SET_SCREEN_WIDTH'
};

export default actionTypes;
