export const paths = {
    HOME: '/',
    MYMUSIC: '/mymusic',
    ZINGCHART: '/zing-chart',
    RADIO: '/radio',
    FOLLOWING: '/following',
    NEW: '/moi-phat-hanh',
    HUB: '/hub',
    TOP100: '/top100',
    MV: '/mv',
    MYSONG: '/mysong',
    PLAYLIST: '/playlist',
    HISTORY: '/history',
    ALBUM: '/album/:title/:playlistId.html',
    PLAYLISTALBUM: '/playlist/:title/:playlistId.html',
    WEEKCHART: '/zing-chart-tuan/:title/:weekchartId.html',
    SINGER: '/:singerName',
    ARTIST_SINGER: '/nghe-si/:singerName',
    SEARCH_ALL: '/tim-kiem/tat-ca',
    SEARCH_SONGS: '/tim-kiem/bai-hat',
    SEARCH_PLAYLIST: '/tim-kiem/playlist',
    SEARCH_ARTIST: '/tim-kiem/artist',
};
