export const routes = {
    home: '/',
    mymusic: '/mymusic',
    zingchart: '/zing-chart',
    radio: '/radio',
    following: '/following',
    new: '/new',
    hub: '/hub',
    top100: '/top100',
    mv: '/mv',
    mysong: '/mysong',
    playlist: '/playlist',
    history: '/history',
    album: '/album/:title/:playlistId.html',
    playlistAlbum: '/playlist/:title/:playlistId.html',
};
